apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../charts/operators
  - ../../charts/infrastructure
  - ../../charts/core-services
  - ../../charts/compute-services

patchesStrategicMerge:
  - values/production-overrides.yaml
