apiVersion: v2
name: openstack-operators
description: OpenStack operators and CRDs
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: pxc-operator
    version: 1.18.0
    repository: https://percona.github.io/percona-helm-charts/
  - name: rabbitmq-cluster-operator
    version: 4.4.34
    repository: https://charts.bitnami.com/bitnami
