apiVersion: v2
name: openstack-compute-services
description: OpenStack compute and additional services
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: nova
    version: 0.3.46
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: heat
    version: 0.3.7
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: horizon
    version: 0.3.15
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: barbican
    version: 0.3.10
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: magnum
    version: 0.2.9
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: manila
    version: 0.1.7
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
  - name: octavia
    version: 0.2.9
    repository: https://tarballs.opendev.org/openstack/openstack-helm/
